services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: hris
      POSTGRES_PASSWORD: hris
      POSTGRES_DB: hris
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    env_file: .env.docker
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
